modLoader="javafml"
loaderVersion="[4,)"
license="MIT"
issueTrackerURL="https://github.com/imndllnuri/easy-sort/issues"

[[mixins]]
config="easy-sort.mixins.json"

[[mods]]
modId="easysort"
version="${version}"
displayName="Easy Sort"
displayURL="https://github.com/imndllnuri/easy-sort"
logoFile="icon.png"
description='''
A lightweight, vanilla-feel inventory and chest sorting mod.
'''
authors="imndllnuri"

[[dependencies.easysort]]
    modId="neoforge"
    type="required"
    versionRange="[21.10,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.easysort]]
    modId="minecraft"
    type="required"
    versionRange="[1.21.11,1.21.12)"
    ordering="NONE"
    side="BOTH"
